### PR TITLE
Added assets for ARMS

### PR DESCRIPTION
**Pull request by Wolfy76700**
- Added multiple sets of assets for ARMS for the Nintendo Switch

  - Base assets and renders by @Frosty_4267 and @LOSER_31_56 (Source: https://drive.google.com/drive/folders/1Ms-Z8-6iyy1D7mDgl3f1JS1GfwiRYtgs)
  - Standard gameplay badges
  - Party Crash badges
  - Character logos

- Added script to download ARMS assets from smash.gg

### CODE REVIEW

**Comment by joaorb64** [comment]
Yo, really nice, the first contribution! Thank you so much!

Seems to me that most things are fine, I'd just suggest the following changes:

- Shouldn't base_files/icon be taken from these https://www.spriters-resource.com/nintendo_switch/arms/sheet/93849/ ? Thinking of how they'd show up in the program for character/skin selection, this looks more appropriate.
- Please add a version to all assets. I believe 1.0 should be fine as I don't think the game will receive more characters. It's mostly for the user to know there was an update to the asset if there is ever one.
- Please add credits under the key "credits" instead of under "description"

For the "type" in assets, I haven't properly documented this one. I'm currently using this in the program to know which asset to use on the character selection dropdown ("icon") and which one to use on the skin selection dropdown ("portrait", but if not found it uses "icon"). I was thinking of using this as a way of having a generic way of mapping assets on `program_state.json` so that the html layouts wouldn't need any code changes to be used, but this idea didn't fully mature yet...

**Comment by Wolfy76700** [comment]
> Yo, really nice, the first contribution! Thank you so much!
> 
> Seems to me that most things are fine, I'd just suggest the following changes:
> 
> * Shouldn't base_files/icon be taken from these https://www.spriters-resource.com/nintendo_switch/arms/sheet/93849/ ? Thinking of how they'd show up in the program for character/skin selection, this looks more appropriate.
> * Please add a version to all assets. I believe 1.0 should be fine as I don't think the game will receive more characters. It's mostly for the user to know there was an update to the asset if there is ever one.
> * Please add credits under the key "credits" instead of under "description"
> 
> For the "type" in assets, I haven't properly documented this one. I'm currently using this in the program to know which asset to use on the character selection dropdown ("icon") and which one to use on the skin selection dropdown ("portrait", but if not found it uses "icon"). I was thinking of using this as a way of having a generic way of mapping assets on `program_state.json` so that the html layouts wouldn't need any code changes to be used, but this idea didn't fully mature yet...

OK, all issues should be fixed now:
- Changed the iconset to the in-game portraits used in Grand Prix mode
- Moved renders to asset pack "full" for display purposes
- Set version for all asset packs to 1.0
- Credits moved to "credits" key in config.json

**Comment by joaorb64** [comment]
Perfect! Thank you so much for the contribution!

**Comment by Wolfy76700** [comment]
You're welcome!

**Pull request merged**
